### ISSUE TITLE
Autocomplete does not repopulate list if 'nothing found'

### ISSUE THREAD

**Issue by timmickey** [HoldMyTicket/RiotMode#1]
To reproduce this issue: use the Autocomplete demo and type in 'asdfff'. Blur (click body or elsewhere). Click on the Autocomplete field again, delete all, type in 'b'. There should be 3 results, but instead you get none, nor do you get a 'Nothing found' message.

**Comment by evan-f** [comment]
Updated the click event handler to open back up with you loses focus / click back in. Should fix this.
