### ISSUE TITLE
Autocomplete - clicking an option behaves different than typing the option

### ISSUE THREAD

**Issue by timmickey** [HoldMyTicket/RiotMode#6]
To reproduce, use the Autocomplete type on the demo and scroll to Punat and click it. Click on 'Punat' and you will still see a full list of options.  
Refresh page.  
Use Autocomplete type. Type in 'Punat' and push 'Enter' on keyboard. Click on 'Punat'. Only the option 'Punat' is available.  

These 2 should behave the same. Lets make them both behave like typing currently does.

**Comment by evan-f** [comment]
Fixed in the new version
